server {
#bn2ol l nginx e3ml server cofiguration    
    listen 80;
#nginx esm3 el incoming requests 3la port 80
#y3ny lma user y3ml https://localhost el request yro7 l nginx 3la port 80  
#w dh motafk m3 compose  
    location / {
        proxy_pass http://app:8000;
    }
#ai request haygy 3la / w ai path t7t / hayro7 el nginx ba3taha ll fastapi application 3la port 8000
#dh el port el fastapi sha8al 3lih gwa app container
#el request haymsh keda:
#browser>localhost:80>nginx:80>proxy_pass>app:8000>Fastapi 
#proxy_pass tawgih eli ba2olo l nginx    
}